apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: デモンストレーション用のサービスです
  labels:
    app: example
spec:
  type: service
  owner: team-a
  lifecycle: production
